// <auto-generated />
using Exercice04.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercice04.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240201183545_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Exercice04.Models.Dragon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dragons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 6,
                            Description = "Le favori des dragons",
                            Nom = "Drogon"
                        },
                        new
                        {
                            Id = 2,
                            Age = 6,
                            Description = "Le dragon mort vivant",
                            Nom = "Viserion"
                        },
                        new
                        {
                            Id = 3,
                            Age = 6,
                            Description = "Le premier dragon a mourir",
                            Nom = "Rhaegal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
